name: Build Android APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Linux Dependencies
        run: |
          sudo apt update
          sudo apt-get install -y --no-install-recommends \
            clang ninja-build libgtk-3-dev libasound2-dev libmpv-dev mpv \
            pkg-config libsecret-1-0 libsecret-1-dev

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Flet
        run: |
          pip install flet

      - name: Build APK (con log dettagliato)
        run: |
          flet build apk rubrica.py --verbose

      - name: Carica l'APK finale nei risultati
        if: always() # Esegue il caricamento anche se trova file parziali
        uses: actions/upload-artifact@v4
        with:
          name: rubrica-android-apk
          path: build/apk/*.apk
